import { CommonModule, DatePipe } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { Notification, NotificationFilters, NotificationService } from '../../core/services/notification.service';

@Component({
  selector: 'app-notification-center', standalone: true, imports: [CommonModule, FormsModule, DatePipe],
  template: `
    <section class="notifications-page">
      <header class="page-header"><div><p class="eyebrow">Module 9 · Notification center</p><h2>Notifications</h2><p>In-app operational alerts returned for your authenticated account.</p></div><div class="header-actions"><button class="btn btn-outline-primary" type="button" (click)="reload()" [disabled]="loading()">{{ loading() ? 'Refreshing…' : 'Refresh' }}</button><button class="btn btn-primary" type="button" (click)="markAllRead()" [disabled]="markingAll() || !unreadCount()">{{ markingAll() ? 'Marking…' : 'Mark all read' }}</button></div></header>
      <section class="filter-panel"><label>Module<select class="form-select" [(ngModel)]="module"><option value="">All modules</option><option *ngFor="let option of moduleOptions" [value]="option">{{ option }}</option></select></label><label>Priority<select class="form-select" [(ngModel)]="priority"><option value="">All priorities</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></label><label>Read status<select class="form-select" [(ngModel)]="readStatus"><option value="">All notifications</option><option value="unread">Unread</option><option value="read">Read</option></select></label><label>From date<input class="form-control" type="date" [(ngModel)]="fromDate"></label><label>To date<input class="form-control" type="date" [(ngModel)]="toDate"></label><button class="btn btn-primary" type="button" (click)="applyFilters()">Apply filters</button></section>
      <div class="summary"><strong>{{ filtered().length }}</strong> shown · <strong>{{ unreadCount() }}</strong> unread</div>
      <div *ngIf="errorMessage()" class="message error-message" role="alert">{{ errorMessage() }}</div>
      <div *ngIf="loading()" class="empty-state">Loading notifications…</div>
      <article *ngFor="let item of filtered()" class="notification-item" [class.unread]="!item.isRead" (click)="open(item)"><div class="priority" [class]="'priority priority-' + item.priority.toLowerCase()">{{ item.priority }}</div><div class="notification-copy"><div class="notification-title"><h3>{{ item.title }}</h3><span>{{ item.relatedModule || item.notificationType }}</span></div><p>{{ item.message }}</p><time>{{ item.createdAt | date:'medium' }}</time></div><button *ngIf="!item.isRead" class="btn btn-outline-primary btn-sm" type="button" (click)="$event.stopPropagation(); markRead(item)">Mark read</button></article>
      <div *ngIf="!loading() && !filtered().length" class="empty-state"><h3>No notifications match these filters</h3><p>Background scans and workflow activity create alerts only when there is a real matching record.</p></div>
    </section>`,
  styles: [`
    .notifications-page{color:var(--vr-navy)}.header-actions{display:flex;gap:.65rem;flex-wrap:wrap}.filter-panel{display:grid;grid-template-columns:repeat(5,minmax(125px,1fr)) auto;gap:.75rem;align-items:end;margin:1.25rem 0;padding:1rem;border:1px solid var(--vr-border);border-radius:16px;background:var(--vr-surface-muted);box-shadow:var(--vr-shadow-sm)}.filter-panel label{display:grid;gap:.35rem}.summary{margin:.8rem 0;color:var(--vr-muted)}.notification-item{display:flex;align-items:flex-start;gap:1rem;margin:.75rem 0;padding:1rem;border:1px solid var(--vr-border);border-radius:15px;background:#fff;cursor:pointer;transition:transform .15s,box-shadow .15s}.notification-item:hover{transform:translateY(-1px);box-shadow:0 8px 20px rgba(31,41,55,.07)}.notification-item.unread{border-left:4px solid var(--vr-primary);background:#fff7f8}.priority{flex:0 0 auto;border-radius:99px;padding:.3rem .55rem;font-size:.7rem;font-weight:800}.priority-high{background:#fee2e2;color:#991b1b}.priority-medium{background:#fef3c7;color:#92400e}.priority-low{background:#dbeafe;color:#1d4ed8}.notification-copy{min-width:0;flex:1}.notification-title{display:flex;justify-content:space-between;gap:.75rem}.notification-title h3{margin:0;font-size:1rem}.notification-title span,time{color:var(--vr-muted);font-size:.78rem}.notification-copy p{margin:.35rem 0;color:#475569}.btn-sm{min-height:36px;padding:0 .7rem;font-size:.8rem}@media(max-width:900px){.filter-panel{grid-template-columns:repeat(2,minmax(0,1fr))}.filter-panel .btn{grid-column:1/-1}}@media(max-width:540px){.filter-panel{grid-template-columns:1fr}.notification-item{gap:.65rem;flex-wrap:wrap}.notification-item .btn{margin-left:auto}}
  `]
})
export class NotificationCenterComponent implements OnInit {
  private readonly service = inject(NotificationService); private readonly router = inject(Router);
  readonly notifications = signal<Notification[]>([]); readonly filtered = signal<Notification[]>([]); readonly unreadCount = signal(0); readonly loading = signal(false); readonly markingAll = signal(false); readonly errorMessage = signal('');
  module = ''; priority = ''; readStatus = ''; fromDate = ''; toDate = ''; readonly moduleOptions = ['Contracts', 'Compliance', 'Procurement', 'Vendor', 'Messages', 'Performance', 'Reliability'];
  ngOnInit(): void { this.reload(); }
  reload(): void { this.loading.set(true); this.errorMessage.set(''); this.service.list(this.apiFilters()).subscribe({next:(result)=>{this.notifications.set(result.items);this.unreadCount.set(result.unreadCount);this.applyLocalFilters();this.loading.set(false);},error:(error)=>{this.errorMessage.set(this.readError(error));this.loading.set(false);}}); }
  applyFilters(): void { this.reload(); }
  markRead(item: Notification): void { if(item.isRead)return; this.service.markRead(item.id).subscribe({next:()=>{this.notifications.update(items=>items.map(value=>value.id===item.id?{...value,isRead:true}:value));this.unreadCount.update(value=>Math.max(value-1,0));this.applyLocalFilters();},error:(error)=>this.errorMessage.set(this.readError(error))}); }
  markAllRead(): void { this.markingAll.set(true);this.service.markAllRead().subscribe({next:()=>{this.notifications.update(items=>items.map(item=>({...item,isRead:true})));this.unreadCount.set(0);this.applyLocalFilters();this.markingAll.set(false);},error:(error)=>{this.errorMessage.set(this.readError(error));this.markingAll.set(false);}}); }
  open(item: Notification): void { const destination=item.link || this.modulePath(item.relatedModule); if(!item.isRead)this.markRead(item); if(destination)this.router.navigateByUrl(destination); }
  private applyLocalFilters(): void { let items=[...this.notifications()]; if(this.fromDate){const start=new Date(`${this.fromDate}T00:00:00`);items=items.filter(item=>item.createdAt&&new Date(item.createdAt)>=start);}if(this.toDate){const end=new Date(`${this.toDate}T23:59:59`);items=items.filter(item=>item.createdAt&&new Date(item.createdAt)<=end);}this.filtered.set(items); }
  private apiFilters(): NotificationFilters { return {module:this.module||undefined,priority:this.priority||undefined,isRead:this.readStatus===''?undefined:this.readStatus==='read'}; }
  private modulePath(module: string | null): string | null { const value=(module||'').toLowerCase(); if(value.includes('contract'))return '/contracts';if(value.includes('compliance'))return '/contracts/compliance';if(value.includes('procurement'))return '/procurement';if(value.includes('message'))return '/messages';if(value.includes('performance'))return '/performance';if(value.includes('reliability'))return '/reliability';if(value.includes('vendor'))return '/vendors';return null; }
  private readError(error: unknown): string { const detail=typeof error==='object'&&error!==null&&'error' in error?(error as {error?:{detail?:unknown}}).error?.detail:null;return typeof detail==='string'?detail:'Unable to load notifications.'; }
}
