import { CommonModule } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';
import { ProcurementRequest, ProcurementService, PurchaseOrderCreatePayload } from '../../core/services/procurement.service';

@Component({ selector: 'app-purchase-order-form', standalone: true, imports: [CommonModule, ReactiveFormsModule, RouterLink], templateUrl: './purchase-order-form.component.html', styleUrl: './purchase-order-form.component.css' })
export class PurchaseOrderFormComponent {
  private readonly fb = inject(FormBuilder); private readonly route = inject(ActivatedRoute); private readonly router = inject(Router); private readonly procurementService = inject(ProcurementService); private readonly authService = inject(AuthService);
  readonly request = signal<ProcurementRequest | null>(null); readonly checkingRequest = signal(false); readonly submitting = signal(false); readonly errorMessage = signal('');
  readonly form = this.fb.nonNullable.group({ procurementRequestId: ['', [Validators.required, Validators.min(1)]], contractId: [''], quantityOrdered: [1, [Validators.required, Validators.min(1)]], unitPrice: [0, [Validators.required, Validators.min(0)]], taxDetails: [0, [Validators.required, Validators.min(0)]], shippingAddress: [''], expectedDeliveryDate: ['', [Validators.required]], paymentTerms: [''] });
  ngOnInit(): void { const requestId = Number(this.route.snapshot.queryParamMap.get('requestId')); if (Number.isInteger(requestId) && requestId > 0) { this.form.patchValue({ procurementRequestId: String(requestId) }); this.checkRequest(); } }
  get readyToCreate(): boolean { const request = this.request(); return !!request && request.approval_status === 'Approved' && !!request.vendor_id; }
  checkRequest(): void { const requestId = Number(this.form.getRawValue().procurementRequestId); if (!Number.isInteger(requestId) || requestId <= 0) { this.request.set(null); return; } this.checkingRequest.set(true); this.errorMessage.set(''); this.procurementService.getRequest(requestId).subscribe({ next: (request) => { this.request.set(request); this.checkingRequest.set(false); }, error: (error: unknown) => { this.request.set(null); this.errorMessage.set(this.readError(error)); this.checkingRequest.set(false); } }); }
  submit(): void { if (this.form.invalid) { this.form.markAllAsTouched(); return; } const requestId = Number(this.form.getRawValue().procurementRequestId); if (this.request()?.id !== requestId) { this.checkRequest(); return; } if (!this.readyToCreate) { this.errorMessage.set('A purchase order requires an approved request with an assigned vendor.'); return; } const value = this.form.getRawValue(); const payload: PurchaseOrderCreatePayload = { procurementRequestId: requestId, contractId: value.contractId === '' ? null : Number(value.contractId), quantityOrdered: Number(value.quantityOrdered), unitPrice: Number(value.unitPrice), taxDetails: Number(value.taxDetails), shippingAddress: value.shippingAddress || null, expectedDeliveryDate: `${value.expectedDeliveryDate}T00:00:00`, paymentTerms: value.paymentTerms || null, createdBy: this.authService.getStoredUser()?.id ?? null }; this.submitting.set(true); this.errorMessage.set(''); this.procurementService.createPurchaseOrder(payload).subscribe({ next: (order) => this.router.navigate(['/procurement/purchase-orders', order.id], { state: { successMessage: 'Purchase order generated successfully.' } }), error: (error: unknown) => { this.errorMessage.set(this.readError(error)); this.submitting.set(false); } }); }
  hasError(name: string, error: string): boolean { const control = this.form.get(name); return !!control && control.touched && control.hasError(error); }
  private readError(error: unknown): string { const detail = typeof error === 'object' && error !== null && 'error' in error ? (error as { error?: { detail?: unknown } }).error?.detail : null; return typeof detail === 'string' ? detail : 'Unable to generate the purchase order. Please try again.'; }
}
