"""align_models_with_requirements_v3

Revision ID: 145083324cb4
Revises: 5e725b13cee9
Create Date: 2026-07-23 21:26:57.491380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '145083324cb4'
down_revision: Union[str, Sequence[str], None] = '5e725b13cee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('vendor_approval_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('action_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_approval_history_action_date'), 'vendor_approval_history', ['action_date'], unique=False)
    op.create_index(op.f('ix_vendor_approval_history_approved_by'), 'vendor_approval_history', ['approved_by'], unique=False)
    op.create_index(op.f('ix_vendor_approval_history_id'), 'vendor_approval_history', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_approval_history_vendor_id'), 'vendor_approval_history', ['vendor_id'], unique=False)
    op.create_table('procurement_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procurement_request_id', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['procurement_request_id'], ['procurement_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_approvals_approved_by'), 'procurement_approvals', ['approved_by'], unique=False)
    op.create_index(op.f('ix_procurement_approvals_id'), 'procurement_approvals', ['id'], unique=False)
    op.create_index(op.f('ix_procurement_approvals_procurement_request_id'), 'procurement_approvals', ['procurement_request_id'], unique=False)
    op.create_table('procurement_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procurement_request_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['procurement_request_id'], ['procurement_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_status_history_changed_at'), 'procurement_status_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_procurement_status_history_changed_by'), 'procurement_status_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_procurement_status_history_id'), 'procurement_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_procurement_status_history_procurement_request_id'), 'procurement_status_history', ['procurement_request_id'], unique=False)
    op.create_table('order_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('dispatch_date', sa.DateTime(), nullable=True),
    sa.Column('expected_delivery_date', sa.DateTime(), nullable=False),
    sa.Column('actual_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.Column('delay_days', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_tracking_delivery_status'), 'order_tracking', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_order_tracking_id'), 'order_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_order_tracking_purchase_order_id'), 'order_tracking', ['purchase_order_id'], unique=True)
    op.add_column('invoices', sa.Column('tax_amount', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('total_amount', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('supporting_document_url', sa.String(length=500), nullable=True))
    op.drop_constraint(op.f('invoices_invoice_number_key'), 'invoices', type_='unique')
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.add_column('procurement_requests', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('procurement_requests', sa.Column('product_name', sa.String(length=255), nullable=False))
    op.add_column('procurement_requests', sa.Column('product_category', sa.String(length=100), nullable=False))
    op.add_column('procurement_requests', sa.Column('unit_of_measurement', sa.String(length=50), nullable=True))
    op.add_column('procurement_requests', sa.Column('estimated_budget', sa.Float(), nullable=False))
    op.add_column('procurement_requests', sa.Column('required_delivery_date', sa.DateTime(), nullable=False))
    op.add_column('procurement_requests', sa.Column('priority', sa.String(length=50), nullable=False))
    op.add_column('procurement_requests', sa.Column('business_justification', sa.String(length=1000), nullable=False))
    op.add_column('procurement_requests', sa.Column('additional_remarks', sa.String(length=1000), nullable=True))
    op.add_column('procurement_requests', sa.Column('approval_remarks', sa.String(length=1000), nullable=True))
    op.add_column('procurement_requests', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('procurement_requests_request_number_key'), 'procurement_requests', type_='unique')
    op.create_index(op.f('ix_procurement_requests_approved_by'), 'procurement_requests', ['approved_by'], unique=False)
    op.create_index(op.f('ix_procurement_requests_priority'), 'procurement_requests', ['priority'], unique=False)
    op.create_index(op.f('ix_procurement_requests_request_number'), 'procurement_requests', ['request_number'], unique=True)
    op.create_index(op.f('ix_procurement_requests_requested_by'), 'procurement_requests', ['requested_by'], unique=False)
    op.create_index(op.f('ix_procurement_requests_vendor_id'), 'procurement_requests', ['vendor_id'], unique=False)
    op.create_foreign_key(None, 'procurement_requests', 'vendors', ['vendor_id'], ['id'])
    op.add_column('purchase_orders', sa.Column('tax_details', sa.Float(), nullable=True))
    op.add_column('purchase_orders', sa.Column('shipping_address', sa.String(length=500), nullable=True))
    op.add_column('purchase_orders', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('purchase_orders', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('purchase_orders', sa.Column('po_date', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('purchase_orders_po_number_key'), 'purchase_orders', type_='unique')
    op.drop_constraint(op.f('purchase_orders_procurement_request_id_key'), 'purchase_orders', type_='unique')
    op.create_index(op.f('ix_purchase_orders_approved_by'), 'purchase_orders', ['approved_by'], unique=False)
    op.create_index(op.f('ix_purchase_orders_created_by'), 'purchase_orders', ['created_by'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_procurement_request_id'), 'purchase_orders', ['procurement_request_id'], unique=True)
    op.create_foreign_key(None, 'purchase_orders', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'purchase_orders', 'users', ['created_by'], ['id'])
    op.add_column('users', sa.Column('mobile_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('employee_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_vendors_approval_status'), 'vendors', ['approval_status'], unique=False)
    op.create_index(op.f('ix_vendors_gst_number'), 'vendors', ['gst_number'], unique=True)
    op.create_index(op.f('ix_vendors_pan_number'), 'vendors', ['pan_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_pan_number'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_gst_number'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_approval_status'), table_name='vendors')
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'employee_id')
    op.drop_column('users', 'mobile_number')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_orders_procurement_request_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_created_by'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_approved_by'), table_name='purchase_orders')
    op.create_unique_constraint(op.f('purchase_orders_procurement_request_id_key'), 'purchase_orders', ['procurement_request_id'])
    op.create_unique_constraint(op.f('purchase_orders_po_number_key'), 'purchase_orders', ['po_number'])
    op.drop_column('purchase_orders', 'po_date')
    op.drop_column('purchase_orders', 'approved_by')
    op.drop_column('purchase_orders', 'created_by')
    op.drop_column('purchase_orders', 'shipping_address')
    op.drop_column('purchase_orders', 'tax_details')
    op.drop_constraint(None, 'procurement_requests', type_='foreignkey')
    op.drop_index(op.f('ix_procurement_requests_vendor_id'), table_name='procurement_requests')
    op.drop_index(op.f('ix_procurement_requests_requested_by'), table_name='procurement_requests')
    op.drop_index(op.f('ix_procurement_requests_request_number'), table_name='procurement_requests')
    op.drop_index(op.f('ix_procurement_requests_priority'), table_name='procurement_requests')
    op.drop_index(op.f('ix_procurement_requests_approved_by'), table_name='procurement_requests')
    op.create_unique_constraint(op.f('procurement_requests_request_number_key'), 'procurement_requests', ['request_number'])
    op.drop_column('procurement_requests', 'vendor_id')
    op.drop_column('procurement_requests', 'approval_remarks')
    op.drop_column('procurement_requests', 'additional_remarks')
    op.drop_column('procurement_requests', 'business_justification')
    op.drop_column('procurement_requests', 'priority')
    op.drop_column('procurement_requests', 'required_delivery_date')
    op.drop_column('procurement_requests', 'estimated_budget')
    op.drop_column('procurement_requests', 'unit_of_measurement')
    op.drop_column('procurement_requests', 'product_category')
    op.drop_column('procurement_requests', 'product_name')
    op.drop_column('procurement_requests', 'title')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.create_unique_constraint(op.f('invoices_invoice_number_key'), 'invoices', ['invoice_number'])
    op.drop_column('invoices', 'supporting_document_url')
    op.drop_column('invoices', 'total_amount')
    op.drop_column('invoices', 'tax_amount')
    op.drop_index(op.f('ix_order_tracking_purchase_order_id'), table_name='order_tracking')
    op.drop_index(op.f('ix_order_tracking_id'), table_name='order_tracking')
    op.drop_index(op.f('ix_order_tracking_delivery_status'), table_name='order_tracking')
    op.drop_table('order_tracking')
    op.drop_index(op.f('ix_procurement_status_history_procurement_request_id'), table_name='procurement_status_history')
    op.drop_index(op.f('ix_procurement_status_history_id'), table_name='procurement_status_history')
    op.drop_index(op.f('ix_procurement_status_history_changed_by'), table_name='procurement_status_history')
    op.drop_index(op.f('ix_procurement_status_history_changed_at'), table_name='procurement_status_history')
    op.drop_table('procurement_status_history')
    op.drop_index(op.f('ix_procurement_approvals_procurement_request_id'), table_name='procurement_approvals')
    op.drop_index(op.f('ix_procurement_approvals_id'), table_name='procurement_approvals')
    op.drop_index(op.f('ix_procurement_approvals_approved_by'), table_name='procurement_approvals')
    op.drop_table('procurement_approvals')
    op.drop_index(op.f('ix_vendor_approval_history_vendor_id'), table_name='vendor_approval_history')
    op.drop_index(op.f('ix_vendor_approval_history_id'), table_name='vendor_approval_history')
    op.drop_index(op.f('ix_vendor_approval_history_approved_by'), table_name='vendor_approval_history')
    op.drop_index(op.f('ix_vendor_approval_history_action_date'), table_name='vendor_approval_history')
    op.drop_table('vendor_approval_history')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
