"""add_contracts_renewals_certifications_compliance

Revision ID: 34d03b0bca5d
Revises: 5694ad64a9c0
Create Date: 2026-07-28 18:59:30.656639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34d03b0bca5d'
down_revision: Union[str, Sequence[str], None] = '5694ad64a9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def create_index_if_not_exists(inspect_obj, tables, index_name, table_name, columns, unique=False):
    if table_name in tables:
        indexes = [idx['name'] for idx in inspect_obj.get_indexes(table_name)]
        if index_name not in indexes:
            op.create_index(index_name, table_name, columns, unique=unique)
    else:
        op.create_index(index_name, table_name, columns, unique=unique)


def drop_index_if_exists(inspect_obj, tables, index_name, table_name):
    if table_name in tables:
        indexes = [idx['name'] for idx in inspect_obj.get_indexes(table_name)]
        if index_name in indexes:
            op.drop_index(index_name, table_name=table_name)


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspect_obj = sa.inspect(conn)
    tables = inspect_obj.get_table_names()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('certification_name', sa.String(length=255), nullable=False),
    sa.Column('certificate_number', sa.String(length=100), nullable=False),
    sa.Column('issuing_authority', sa.String(length=255), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    create_index_if_not_exists(inspect_obj, tables, 'ix_certifications_expiry_date', 'certifications', ['expiry_date'], unique=False)
    create_index_if_not_exists(inspect_obj, tables, 'ix_certifications_id', 'certifications', ['id'], unique=False)
    create_index_if_not_exists(inspect_obj, tables, 'ix_certifications_vendor_id', 'certifications', ['vendor_id'], unique=False)
    op.create_table('compliance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('compliance_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('verification_date', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    create_index_if_not_exists(inspect_obj, tables, 'ix_compliance_records_id', 'compliance_records', ['id'], unique=False)
    create_index_if_not_exists(inspect_obj, tables, 'ix_compliance_records_status', 'compliance_records', ['status'], unique=False)
    create_index_if_not_exists(inspect_obj, tables, 'ix_compliance_records_vendor_id', 'compliance_records', ['vendor_id'], unique=False)
    op.create_table('contract_renewals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('renewal_date', sa.DateTime(), nullable=True),
    sa.Column('new_end_date', sa.DateTime(), nullable=False),
    sa.Column('renewal_value', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    create_index_if_not_exists(inspect_obj, tables, 'ix_contract_renewals_contract_id', 'contract_renewals', ['contract_id'], unique=False)
    create_index_if_not_exists(inspect_obj, tables, 'ix_contract_renewals_id', 'contract_renewals', ['id'], unique=False)
    op.add_column('contracts', sa.Column('contract_number', sa.String(length=100), nullable=True))
    op.execute("UPDATE contracts SET contract_number = 'CON-' || id WHERE contract_number IS NULL")
    op.alter_column('contracts', 'contract_number', nullable=False)
    op.add_column('contracts', sa.Column('procurement_category', sa.String(length=100), nullable=True))
    op.add_column('contracts', sa.Column('payment_terms', sa.String(length=255), nullable=True))
    op.add_column('contracts', sa.Column('sla', sa.String(length=500), nullable=True))
    op.add_column('contracts', sa.Column('warranty_details', sa.String(length=500), nullable=True))
    op.add_column('contracts', sa.Column('responsible_manager', sa.String(length=255), nullable=True))
    op.add_column('contracts', sa.Column('document_url', sa.String(length=500), nullable=True))
    create_index_if_not_exists(inspect_obj, tables, 'ix_contracts_contract_number', 'contracts', ['contract_number'], unique=True)
    create_index_if_not_exists(inspect_obj, tables, 'ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=True)
    op.alter_column('procurement_requests', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('procurement_requests', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('procurement_requests', 'product_category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('procurement_requests', 'estimated_budget',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('procurement_requests', 'required_delivery_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('procurement_requests', 'priority',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('procurement_requests', 'business_justification',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.drop_constraint(op.f('procurement_requests_request_number_key'), 'procurement_requests', type_='unique')
    create_index_if_not_exists(inspect_obj, tables, 'ix_procurement_requests_approved_by', 'procurement_requests', ['approved_by'], unique=False)
    create_index_if_not_exists(inspect_obj, tables, 'ix_procurement_requests_priority', 'procurement_requests', ['priority'], unique=False)
    create_index_if_not_exists(inspect_obj, tables, 'ix_procurement_requests_request_number', 'procurement_requests', ['request_number'], unique=True)
    create_index_if_not_exists(inspect_obj, tables, 'ix_procurement_requests_requested_by', 'procurement_requests', ['requested_by'], unique=False)
    create_index_if_not_exists(inspect_obj, tables, 'ix_procurement_requests_vendor_id', 'procurement_requests', ['vendor_id'], unique=False)
    op.create_foreign_key(None, 'procurement_requests', 'vendors', ['vendor_id'], ['id'])
    op.add_column('purchase_orders', sa.Column('tax_details', sa.Float(), nullable=True))
    op.add_column('purchase_orders', sa.Column('shipping_address', sa.String(length=500), nullable=True))
    op.add_column('purchase_orders', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('purchase_orders', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('purchase_orders', sa.Column('po_date', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('purchase_orders_po_number_key'), 'purchase_orders', type_='unique')
    op.drop_constraint(op.f('purchase_orders_procurement_request_id_key'), 'purchase_orders', type_='unique')
    create_index_if_not_exists(inspect_obj, tables, 'ix_purchase_orders_approved_by', 'purchase_orders', ['approved_by'], unique=False)
    create_index_if_not_exists(inspect_obj, tables, 'ix_purchase_orders_created_by', 'purchase_orders', ['created_by'], unique=False)
    create_index_if_not_exists(inspect_obj, tables, 'ix_purchase_orders_po_number', 'purchase_orders', ['po_number'], unique=True)
    create_index_if_not_exists(inspect_obj, tables, 'ix_purchase_orders_procurement_request_id', 'purchase_orders', ['procurement_request_id'], unique=True)
    op.create_foreign_key(None, 'purchase_orders', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'purchase_orders', 'users', ['approved_by'], ['id'])
    op.add_column('users', sa.Column('mobile_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('employee_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    op.add_column('vendor_approval_history', sa.Column('action_date', sa.DateTime(), nullable=True))
    create_index_if_not_exists(inspect_obj, tables, 'ix_vendor_approval_history_acted_by', 'vendor_approval_history', ['acted_by'], unique=False)
    create_index_if_not_exists(inspect_obj, tables, 'ix_vendor_approval_history_action_date', 'vendor_approval_history', ['action_date'], unique=False)
    op.drop_column('vendor_approval_history', 'acted_at')
    create_index_if_not_exists(inspect_obj, tables, 'ix_vendors_approval_status', 'vendors', ['approval_status'], unique=False)
    create_index_if_not_exists(inspect_obj, tables, 'ix_vendors_gst_number', 'vendors', ['gst_number'], unique=True)
    create_index_if_not_exists(inspect_obj, tables, 'ix_vendors_pan_number', 'vendors', ['pan_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    conn = op.get_bind()
    inspect_obj = sa.inspect(conn)
    tables = inspect_obj.get_table_names()
    # ### commands auto generated by Alembic - please adjust! ###
    drop_index_if_exists(inspect_obj, tables, 'ix_vendors_pan_number', 'vendors')
    drop_index_if_exists(inspect_obj, tables, 'ix_vendors_gst_number', 'vendors')
    drop_index_if_exists(inspect_obj, tables, 'ix_vendors_approval_status', 'vendors')
    op.add_column('vendor_approval_history', sa.Column('acted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    drop_index_if_exists(inspect_obj, tables, 'ix_vendor_approval_history_action_date', 'vendor_approval_history')
    drop_index_if_exists(inspect_obj, tables, 'ix_vendor_approval_history_acted_by', 'vendor_approval_history')
    op.drop_column('vendor_approval_history', 'action_date')
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'employee_id')
    op.drop_column('users', 'mobile_number')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    drop_index_if_exists(inspect_obj, tables, 'ix_purchase_orders_procurement_request_id', 'purchase_orders')
    drop_index_if_exists(inspect_obj, tables, 'ix_purchase_orders_po_number', 'purchase_orders')
    drop_index_if_exists(inspect_obj, tables, 'ix_purchase_orders_created_by', 'purchase_orders')
    drop_index_if_exists(inspect_obj, tables, 'ix_purchase_orders_approved_by', 'purchase_orders')
    op.create_unique_constraint(op.f('purchase_orders_procurement_request_id_key'), 'purchase_orders', ['procurement_request_id'])
    op.create_unique_constraint(op.f('purchase_orders_po_number_key'), 'purchase_orders', ['po_number'])
    op.drop_column('purchase_orders', 'po_date')
    op.drop_column('purchase_orders', 'approved_by')
    op.drop_column('purchase_orders', 'created_by')
    op.drop_column('purchase_orders', 'shipping_address')
    op.drop_column('purchase_orders', 'tax_details')
    op.drop_constraint(None, 'procurement_requests', type_='foreignkey')
    drop_index_if_exists(inspect_obj, tables, 'ix_procurement_requests_vendor_id', 'procurement_requests')
    drop_index_if_exists(inspect_obj, tables, 'ix_procurement_requests_requested_by', 'procurement_requests')
    drop_index_if_exists(inspect_obj, tables, 'ix_procurement_requests_request_number', 'procurement_requests')
    drop_index_if_exists(inspect_obj, tables, 'ix_procurement_requests_priority', 'procurement_requests')
    drop_index_if_exists(inspect_obj, tables, 'ix_procurement_requests_approved_by', 'procurement_requests')
    op.create_unique_constraint(op.f('procurement_requests_request_number_key'), 'procurement_requests', ['request_number'])
    op.alter_column('procurement_requests', 'business_justification',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('procurement_requests', 'priority',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('procurement_requests', 'required_delivery_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('procurement_requests', 'estimated_budget',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('procurement_requests', 'product_category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('procurement_requests', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('procurement_requests', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    drop_index_if_exists(inspect_obj, tables, 'ix_invoices_invoice_number', 'invoices')
    drop_index_if_exists(inspect_obj, tables, 'ix_contracts_contract_number', 'contracts')
    op.drop_column('contracts', 'document_url')
    op.drop_column('contracts', 'responsible_manager')
    op.drop_column('contracts', 'warranty_details')
    op.drop_column('contracts', 'sla')
    op.drop_column('contracts', 'payment_terms')
    op.drop_column('contracts', 'procurement_category')
    op.drop_column('contracts', 'contract_number')
    drop_index_if_exists(inspect_obj, tables, 'ix_contract_renewals_id', 'contract_renewals')
    drop_index_if_exists(inspect_obj, tables, 'ix_contract_renewals_contract_id', 'contract_renewals')
    op.drop_table('contract_renewals')
    drop_index_if_exists(inspect_obj, tables, 'ix_compliance_records_vendor_id', 'compliance_records')
    drop_index_if_exists(inspect_obj, tables, 'ix_compliance_records_status', 'compliance_records')
    drop_index_if_exists(inspect_obj, tables, 'ix_compliance_records_id', 'compliance_records')
    op.drop_table('compliance_records')
    drop_index_if_exists(inspect_obj, tables, 'ix_certifications_vendor_id', 'certifications')
    drop_index_if_exists(inspect_obj, tables, 'ix_certifications_id', 'certifications')
    drop_index_if_exists(inspect_obj, tables, 'ix_certifications_expiry_date', 'certifications')
    op.drop_table('certifications')
    # ### end Alembic commands ###
