"""add communications table

Revision ID: 597e1679b425
Revises: dde41bf43135
Create Date: 2026-07-18 11:29:58.362604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '597e1679b425'
down_revision: Union[str, Sequence[str], None] = 'dde41bf43135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('procurement_request_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['procurement_request_id'], ['procurement_requests.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communications_created_at'), 'communications', ['created_at'], unique=False)
    op.create_index(op.f('ix_communications_id'), 'communications', ['id'], unique=False)
    op.create_index(op.f('ix_communications_procurement_request_id'), 'communications', ['procurement_request_id'], unique=False)
    op.create_index(op.f('ix_communications_sender_id'), 'communications', ['sender_id'], unique=False)
    op.create_index(op.f('ix_communications_vendor_id'), 'communications', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communications_vendor_id'), table_name='communications')
    op.drop_index(op.f('ix_communications_sender_id'), table_name='communications')
    op.drop_index(op.f('ix_communications_procurement_request_id'), table_name='communications')
    op.drop_index(op.f('ix_communications_id'), table_name='communications')
    op.drop_index(op.f('ix_communications_created_at'), table_name='communications')
    op.drop_table('communications')
    # ### end Alembic commands ###
