"""add content_type and uploaded_by to vendor_documents

Revision ID: 5b3b58ff7347
Revises: 5e725b13cee9
Create Date: 2026-07-27 20:00:32.776701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b3b58ff7347'
down_revision: Union[str, Sequence[str], None] = '5e725b13cee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_approval_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('acted_by', sa.Integer(), nullable=True),
    sa.Column('acted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_approval_history_id'), 'vendor_approval_history', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_approval_history_vendor_id'), 'vendor_approval_history', ['vendor_id'], unique=False)
    op.add_column('vendor_documents', sa.Column('content_type', sa.String(length=100), nullable=True))
    op.add_column('vendor_documents', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vendor_documents', 'users', ['uploaded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendor_documents', type_='foreignkey')
    op.drop_column('vendor_documents', 'uploaded_by')
    op.drop_column('vendor_documents', 'content_type')
    op.drop_index(op.f('ix_vendor_approval_history_vendor_id'), table_name='vendor_approval_history')
    op.drop_index(op.f('ix_vendor_approval_history_id'), table_name='vendor_approval_history')
    op.drop_table('vendor_approval_history')
    # ### end Alembic commands ###
