"""change product_quality_evaluations rating fields to numeric types

Revision ID: 5e725b13cee9
Revises: 5e77edde8a09
Create Date: 2026-07-19 19:26:58.230344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e725b13cee9'
down_revision: Union[str, Sequence[str], None] = '5e77edde8a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_quality_evaluations', 'material_quality',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='material_quality::double precision')
    op.alter_column('product_quality_evaluations', 'packaging_quality',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='packaging_quality::double precision')
    op.alter_column('product_quality_evaluations', 'quantity_accuracy',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='quantity_accuracy::double precision')
    op.alter_column('product_quality_evaluations', 'specification_compliance',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='specification_compliance::double precision')
    op.alter_column('product_quality_evaluations', 'product_defects',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='product_defects::integer')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_quality_evaluations', 'product_defects',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('product_quality_evaluations', 'specification_compliance',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('product_quality_evaluations', 'quantity_accuracy',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('product_quality_evaluations', 'packaging_quality',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('product_quality_evaluations', 'material_quality',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
