"""align communication_logs, vendor_rankings, performance_records with Sonali's scoring service fields

Revision ID: 5e77edde8a09
Revises: 6c65705712b4
Create Date: 2026-07-19 19:12:05.459040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e77edde8a09'
down_revision: Union[str, Sequence[str], None] = '6c65705712b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communication_logs', sa.Column('response_duration_minutes', sa.Integer(), nullable=True))
    op.drop_column('communication_logs', 'response_duration_hours')
    op.add_column('performance_records', sa.Column('total_completed_orders', sa.Integer(), nullable=True))
    op.add_column('performance_records', sa.Column('on_time_delivery_rate', sa.Float(), nullable=True))
    op.add_column('performance_records', sa.Column('delayed_delivery_count', sa.Integer(), nullable=True))
    op.add_column('performance_records', sa.Column('average_quality_score', sa.Float(), nullable=True))
    op.add_column('performance_records', sa.Column('average_response_time', sa.Float(), nullable=True))
    op.add_column('performance_records', sa.Column('average_service_rating_score', sa.Float(), nullable=True))
    op.add_column('performance_records', sa.Column('overall_performance_score', sa.Float(), nullable=True))
    op.add_column('performance_records', sa.Column('performance_status', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_performance_records_performance_status'), 'performance_records', ['performance_status'], unique=False)
    op.create_index(op.f('ix_performance_records_vendor_id'), 'performance_records', ['vendor_id'], unique=True)
    op.drop_constraint(op.f('performance_records_purchase_order_id_fkey'), 'performance_records', type_='foreignkey')
    op.drop_column('performance_records', 'on_time_delivery')
    op.drop_column('performance_records', 'overall_score')
    op.drop_column('performance_records', 'compliance_score')
    op.drop_column('performance_records', 'purchase_order_id')
    op.drop_column('performance_records', 'communication_score')
    op.drop_column('performance_records', 'risk_level')
    op.drop_column('performance_records', 'quality_rating')
    op.add_column('vendor_rankings', sa.Column('service_rating_score', sa.Float(), nullable=True))
    op.add_column('vendor_rankings', sa.Column('rank_position', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_vendor_rankings_vendor_rank'), table_name='vendor_rankings')
    op.create_index(op.f('ix_vendor_rankings_rank_position'), 'vendor_rankings', ['rank_position'], unique=False)
    op.drop_column('vendor_rankings', 'vendor_rank')
    op.drop_column('vendor_rankings', 'service_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_rankings', sa.Column('service_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('vendor_rankings', sa.Column('vendor_rank', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_vendor_rankings_rank_position'), table_name='vendor_rankings')
    op.create_index(op.f('ix_vendor_rankings_vendor_rank'), 'vendor_rankings', ['vendor_rank'], unique=False)
    op.drop_column('vendor_rankings', 'rank_position')
    op.drop_column('vendor_rankings', 'service_rating_score')
    op.add_column('performance_records', sa.Column('quality_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('performance_records', sa.Column('risk_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('performance_records', sa.Column('communication_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('performance_records', sa.Column('purchase_order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('performance_records', sa.Column('compliance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('performance_records', sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('performance_records', sa.Column('on_time_delivery', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('performance_records_purchase_order_id_fkey'), 'performance_records', 'purchase_orders', ['purchase_order_id'], ['id'])
    op.drop_index(op.f('ix_performance_records_vendor_id'), table_name='performance_records')
    op.drop_index(op.f('ix_performance_records_performance_status'), table_name='performance_records')
    op.drop_column('performance_records', 'performance_status')
    op.drop_column('performance_records', 'overall_performance_score')
    op.drop_column('performance_records', 'average_service_rating_score')
    op.drop_column('performance_records', 'average_response_time')
    op.drop_column('performance_records', 'average_quality_score')
    op.drop_column('performance_records', 'delayed_delivery_count')
    op.drop_column('performance_records', 'on_time_delivery_rate')
    op.drop_column('performance_records', 'total_completed_orders')
    op.add_column('communication_logs', sa.Column('response_duration_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('communication_logs', 'response_duration_minutes')
    # ### end Alembic commands ###
