"""add_reliability_tables

Revision ID: 605aec7d0e6b
Revises: 145083324cb4
Create Date: 2026-07-28 18:42:54.160936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605aec7d0e6b'
down_revision: Union[str, Sequence[str], None] = '145083324cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema safely."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if not inspector.has_table('performance_trends'):
        op.create_table('performance_trends',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vendor_id', sa.Integer(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('month', sa.Integer(), nullable=False),
        sa.Column('reliability_score', sa.Float(), nullable=True),
        sa.Column('delivery_score', sa.Float(), nullable=True),
        sa.Column('quality_score', sa.Float(), nullable=True),
        sa.Column('communication_score', sa.Float(), nullable=True),
        sa.Column('compliance_score', sa.Float(), nullable=True),
        sa.Column('issue_resolution_score', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_performance_trends_id'), 'performance_trends', ['id'], unique=False)
        op.create_index(op.f('ix_performance_trends_vendor_id'), 'performance_trends', ['vendor_id'], unique=False)

    if not inspector.has_table('procurement_recommendations'):
        op.create_table('procurement_recommendations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vendor_id', sa.Integer(), nullable=False),
        sa.Column('reliability_score', sa.Float(), nullable=True),
        sa.Column('risk_level', sa.String(length=50), nullable=True),
        sa.Column('recommendation_status', sa.String(length=100), nullable=True),
        sa.Column('reason', sa.String(length=500), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_procurement_recommendations_id'), 'procurement_recommendations', ['id'], unique=False)
        op.create_index(op.f('ix_procurement_recommendations_risk_level'), 'procurement_recommendations', ['risk_level'], unique=False)
        op.create_index(op.f('ix_procurement_recommendations_vendor_id'), 'procurement_recommendations', ['vendor_id'], unique=True)

    if not inspector.has_table('vendor_reliability'):
        op.create_table('vendor_reliability',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vendor_id', sa.Integer(), nullable=False),
        sa.Column('delivery_score', sa.Float(), nullable=True),
        sa.Column('quality_score', sa.Float(), nullable=True),
        sa.Column('communication_score', sa.Float(), nullable=True),
        sa.Column('compliance_score', sa.Float(), nullable=True),
        sa.Column('issue_resolution_score', sa.Float(), nullable=True),
        sa.Column('reliability_score', sa.Float(), nullable=True),
        sa.Column('risk_level', sa.String(length=50), nullable=True),
        sa.Column('recommendation', sa.String(length=500), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_vendor_reliability_id'), 'vendor_reliability', ['id'], unique=False)
        op.create_index(op.f('ix_vendor_reliability_risk_level'), 'vendor_reliability', ['risk_level'], unique=False)
        op.create_index(op.f('ix_vendor_reliability_vendor_id'), 'vendor_reliability', ['vendor_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_reliability_vendor_id'), table_name='vendor_reliability')
    op.drop_index(op.f('ix_vendor_reliability_risk_level'), table_name='vendor_reliability')
    op.drop_index(op.f('ix_vendor_reliability_id'), table_name='vendor_reliability')
    op.drop_table('vendor_reliability')
    op.drop_index(op.f('ix_procurement_recommendations_vendor_id'), table_name='procurement_recommendations')
    op.drop_index(op.f('ix_procurement_recommendations_risk_level'), table_name='procurement_recommendations')
    op.drop_index(op.f('ix_procurement_recommendations_id'), table_name='procurement_recommendations')
    op.drop_table('procurement_recommendations')
    op.drop_index(op.f('ix_performance_trends_vendor_id'), table_name='performance_trends')
    op.drop_index(op.f('ix_performance_trends_id'), table_name='performance_trends')
    op.drop_table('performance_trends')
    # ### end Alembic commands ###
