"""add vendor_contacts table

Revision ID: 60d6f268f247
Revises: 6f7db1c46089
Create Date: 2026-07-17 05:49:25.962020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d6f268f247'
down_revision: Union[str, Sequence[str], None] = '6f7db1c46089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('contact_person_name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_contacts_id'), 'vendor_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_contacts_vendor_id'), 'vendor_contacts', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_contacts_vendor_id'), table_name='vendor_contacts')
    op.drop_index(op.f('ix_vendor_contacts_id'), table_name='vendor_contacts')
    op.drop_table('vendor_contacts')
    # ### end Alembic commands ###
