"""split procurement_orders into procurement_requests and purchase_orders

Revision ID: 610b715f9fb0
Revises: cd231c6ff38a
Create Date: 2026-07-18 11:08:57.912952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '610b715f9fb0'
down_revision: Union[str, Sequence[str], None] = 'cd231c6ff38a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_number', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('item_description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('approval_status', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_number')
    )
    op.create_index(op.f('ix_procurement_requests_approval_status'), 'procurement_requests', ['approval_status'], unique=False)
    op.create_index(op.f('ix_procurement_requests_id'), 'procurement_requests', ['id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procurement_request_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('expected_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('actual_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('po_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['procurement_request_id'], ['procurement_requests.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number'),
    sa.UniqueConstraint('procurement_request_id')
    )
    op.create_index(op.f('ix_purchase_orders_vendor_id'), 'purchase_orders', ['vendor_id'], unique=False)

    # Fix performance_records FIRST — drop old FK before dropping procurement_orders
    op.add_column('performance_records', sa.Column('purchase_order_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('performance_records_procurement_order_id_fkey'), 'performance_records', type_='foreignkey')
    op.create_foreign_key(None, 'performance_records', 'purchase_orders', ['purchase_order_id'], ['id'])
    op.drop_column('performance_records', 'procurement_order_id')

    # Now safe to drop procurement_orders
    op.drop_index(op.f('ix_procurement_orders_id'), table_name='procurement_orders')
    op.drop_table('procurement_orders')
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_records', sa.Column('procurement_order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'performance_records', type_='foreignkey')
    op.create_foreign_key(op.f('performance_records_procurement_order_id_fkey'), 'performance_records', 'procurement_orders', ['procurement_order_id'], ['id'])
    op.drop_column('performance_records', 'purchase_order_id')
    op.create_table('procurement_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('item_description', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('order_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expected_delivery_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('actual_delivery_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('procurement_orders_contract_id_fkey')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('procurement_orders_vendor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('procurement_orders_pkey')),
    sa.UniqueConstraint('order_number', name=op.f('procurement_orders_order_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_procurement_orders_id'), 'procurement_orders', ['id'], unique=False)
    op.drop_index(op.f('ix_purchase_orders_vendor_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_procurement_requests_id'), table_name='procurement_requests')
    op.drop_index(op.f('ix_procurement_requests_approval_status'), table_name='procurement_requests')
    op.drop_table('procurement_requests')
    # ### end Alembic commands ###
