"""add Module 4 vendor performance tables: delivery_performance, product_quality_evaluations, communication_logs, service_ratings, vendor_rankings

Revision ID: 6c65705712b4
Revises: 597e1679b425
Create Date: 2026-07-19 15:17:06.404447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c65705712b4'
down_revision: Union[str, Sequence[str], None] = '597e1679b425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('overall_performance_score', sa.Float(), nullable=True),
    sa.Column('delivery_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('communication_score', sa.Float(), nullable=True),
    sa.Column('service_score', sa.Float(), nullable=True),
    sa.Column('vendor_rank', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_rankings_id'), 'vendor_rankings', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_rankings_vendor_id'), 'vendor_rankings', ['vendor_id'], unique=True)
    op.create_index(op.f('ix_vendor_rankings_vendor_rank'), 'vendor_rankings', ['vendor_rank'], unique=False)
    op.create_table('communication_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('message_sent_time', sa.DateTime(), nullable=True),
    sa.Column('vendor_response_time', sa.DateTime(), nullable=True),
    sa.Column('response_duration_hours', sa.Integer(), nullable=True),
    sa.Column('communication_status', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_logs_communication_status'), 'communication_logs', ['communication_status'], unique=False)
    op.create_index(op.f('ix_communication_logs_id'), 'communication_logs', ['id'], unique=False)
    op.create_index(op.f('ix_communication_logs_purchase_order_id'), 'communication_logs', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_communication_logs_vendor_id'), 'communication_logs', ['vendor_id'], unique=False)
    op.create_table('delivery_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('expected_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('actual_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('delay_days', sa.Integer(), nullable=True),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_performance_delivery_status'), 'delivery_performance', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_delivery_performance_id'), 'delivery_performance', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_performance_purchase_order_id'), 'delivery_performance', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_delivery_performance_vendor_id'), 'delivery_performance', ['vendor_id'], unique=False)
    op.create_table('product_quality_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('inspection_date', sa.DateTime(), nullable=True),
    sa.Column('material_quality', sa.String(length=50), nullable=True),
    sa.Column('packaging_quality', sa.String(length=50), nullable=True),
    sa.Column('quantity_accuracy', sa.String(length=50), nullable=True),
    sa.Column('specification_compliance', sa.String(length=50), nullable=True),
    sa.Column('product_defects', sa.String(length=500), nullable=True),
    sa.Column('overall_quality_rating', sa.Float(), nullable=True),
    sa.Column('inspector_remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_quality_evaluations_id'), 'product_quality_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_product_quality_evaluations_purchase_order_id'), 'product_quality_evaluations', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_product_quality_evaluations_vendor_id'), 'product_quality_evaluations', ['vendor_id'], unique=False)
    op.create_table('service_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('professionalism', sa.Float(), nullable=True),
    sa.Column('customer_support', sa.Float(), nullable=True),
    sa.Column('documentation_quality', sa.Float(), nullable=True),
    sa.Column('flexibility', sa.Float(), nullable=True),
    sa.Column('communication_effectiveness', sa.Float(), nullable=True),
    sa.Column('issue_resolution', sa.Float(), nullable=True),
    sa.Column('overall_service_rating', sa.Float(), nullable=True),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_ratings_id'), 'service_ratings', ['id'], unique=False)
    op.create_index(op.f('ix_service_ratings_purchase_order_id'), 'service_ratings', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_service_ratings_vendor_id'), 'service_ratings', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_ratings_vendor_id'), table_name='service_ratings')
    op.drop_index(op.f('ix_service_ratings_purchase_order_id'), table_name='service_ratings')
    op.drop_index(op.f('ix_service_ratings_id'), table_name='service_ratings')
    op.drop_table('service_ratings')
    op.drop_index(op.f('ix_product_quality_evaluations_vendor_id'), table_name='product_quality_evaluations')
    op.drop_index(op.f('ix_product_quality_evaluations_purchase_order_id'), table_name='product_quality_evaluations')
    op.drop_index(op.f('ix_product_quality_evaluations_id'), table_name='product_quality_evaluations')
    op.drop_table('product_quality_evaluations')
    op.drop_index(op.f('ix_delivery_performance_vendor_id'), table_name='delivery_performance')
    op.drop_index(op.f('ix_delivery_performance_purchase_order_id'), table_name='delivery_performance')
    op.drop_index(op.f('ix_delivery_performance_id'), table_name='delivery_performance')
    op.drop_index(op.f('ix_delivery_performance_delivery_status'), table_name='delivery_performance')
    op.drop_table('delivery_performance')
    op.drop_index(op.f('ix_communication_logs_vendor_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_purchase_order_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_communication_status'), table_name='communication_logs')
    op.drop_table('communication_logs')
    op.drop_index(op.f('ix_vendor_rankings_vendor_rank'), table_name='vendor_rankings')
    op.drop_index(op.f('ix_vendor_rankings_vendor_id'), table_name='vendor_rankings')
    op.drop_index(op.f('ix_vendor_rankings_id'), table_name='vendor_rankings')
    op.drop_table('vendor_rankings')
    # ### end Alembic commands ###
