"""add vendor_categories table and link to vendor

Revision ID: 6f7db1c46089
Revises: 84e5150a5138
Create Date: 2026-07-15 19:42:19.569500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7db1c46089'
down_revision: Union[str, Sequence[str], None] = '84e5150a5138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_categories_id'), 'vendor_categories', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_categories_name'), 'vendor_categories', ['name'], unique=True)

    # Insert a default category so existing vendors have something to point to
    op.execute("INSERT INTO vendor_categories (name, description, is_active) VALUES ('Uncategorized', 'Default category for existing vendors', true)")

    # Add column as nullable first
    op.add_column('vendors', sa.Column('category_id', sa.Integer(), nullable=True))

    # Fill existing vendors with the default category
    op.execute("UPDATE vendors SET category_id = (SELECT id FROM vendor_categories WHERE name = 'Uncategorized')")

    # Now make it NOT NULL
    op.alter_column('vendors', 'category_id', nullable=False)

    op.create_index(op.f('ix_vendors_category_id'), 'vendors', ['category_id'], unique=False)
    op.create_index(op.f('ix_vendors_vendor_status'), 'vendors', ['vendor_status'], unique=False)
    op.create_foreign_key(None, 'vendors', 'vendor_categories', ['category_id'], ['id'])
    op.drop_column('vendors', 'vendor_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('vendor_category', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vendors', type_='foreignkey')
    op.drop_index(op.f('ix_vendors_vendor_status'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_category_id'), table_name='vendors')
    op.drop_column('vendors', 'category_id')
    op.drop_index(op.f('ix_vendor_categories_name'), table_name='vendor_categories')
    op.drop_index(op.f('ix_vendor_categories_id'), table_name='vendor_categories')
    op.drop_table('vendor_categories')
    # ### end Alembic commands ###
