"""add Module 5 vendor reliability tables

Revision ID: c2db7eff190a
Revises: 15ba89028e5b
Create Date: 2026-07-28 18:27:58.785335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2db7eff190a'
down_revision: Union[str, Sequence[str], None] = '15ba89028e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_score', sa.Float(), nullable=True),
    sa.Column('recommendation_status', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['vendor_categories.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_recommendations_category_id'), 'procurement_recommendations', ['category_id'], unique=False)
    op.create_index(op.f('ix_procurement_recommendations_generated_at'), 'procurement_recommendations', ['generated_at'], unique=False)
    op.create_index(op.f('ix_procurement_recommendations_id'), 'procurement_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_procurement_recommendations_recommendation_status'), 'procurement_recommendations', ['recommendation_status'], unique=False)
    op.create_index(op.f('ix_procurement_recommendations_vendor_id'), 'procurement_recommendations', ['vendor_id'], unique=False)
    op.create_table('procurement_risk_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('risk_reason', sa.String(length=500), nullable=True),
    sa.Column('requires_warning', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_risk_levels_id'), 'procurement_risk_levels', ['id'], unique=False)
    op.create_index(op.f('ix_procurement_risk_levels_risk_level'), 'procurement_risk_levels', ['risk_level'], unique=False)
    op.create_index(op.f('ix_procurement_risk_levels_vendor_id'), 'procurement_risk_levels', ['vendor_id'], unique=True)
    op.create_table('reliability_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('delivery_trend', sa.String(length=50), nullable=True),
    sa.Column('quality_trend', sa.String(length=50), nullable=True),
    sa.Column('communication_trend', sa.String(length=50), nullable=True),
    sa.Column('compliance_trend', sa.String(length=50), nullable=True),
    sa.Column('issue_resolution_trend', sa.String(length=50), nullable=True),
    sa.Column('recorded_month', sa.String(length=20), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reliability_history_id'), 'reliability_history', ['id'], unique=False)
    op.create_index(op.f('ix_reliability_history_recorded_at'), 'reliability_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_reliability_history_vendor_id'), 'reliability_history', ['vendor_id'], unique=False)
    op.create_table('supplier_reliability_ranking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_reliability_ranking_id'), 'supplier_reliability_ranking', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_reliability_ranking_rank_position'), 'supplier_reliability_ranking', ['rank_position'], unique=False)
    op.create_index(op.f('ix_supplier_reliability_ranking_vendor_id'), 'supplier_reliability_ranking', ['vendor_id'], unique=True)
    op.create_table('vendor_reliability_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('delivery_factor', sa.Float(), nullable=True),
    sa.Column('quality_factor', sa.Float(), nullable=True),
    sa.Column('communication_factor', sa.Float(), nullable=True),
    sa.Column('compliance_factor', sa.Float(), nullable=True),
    sa.Column('purchase_history_factor', sa.Float(), nullable=True),
    sa.Column('issue_resolution_factor', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('last_calculated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_reliability_scores_id'), 'vendor_reliability_scores', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_reliability_scores_risk_level'), 'vendor_reliability_scores', ['risk_level'], unique=False)
    op.create_index(op.f('ix_vendor_reliability_scores_vendor_id'), 'vendor_reliability_scores', ['vendor_id'], unique=True)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.alter_column('procurement_requests', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('procurement_requests', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('procurement_requests', 'product_category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('procurement_requests', 'estimated_budget',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('procurement_requests', 'required_delivery_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('procurement_requests', 'priority',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('procurement_requests', 'business_justification',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.drop_constraint(op.f('procurement_requests_request_number_key'), 'procurement_requests', type_='unique')
    op.create_index(op.f('ix_procurement_requests_approved_by'), 'procurement_requests', ['approved_by'], unique=False)
    op.create_index(op.f('ix_procurement_requests_priority'), 'procurement_requests', ['priority'], unique=False)
    op.create_index(op.f('ix_procurement_requests_request_number'), 'procurement_requests', ['request_number'], unique=True)
    op.create_index(op.f('ix_procurement_requests_requested_by'), 'procurement_requests', ['requested_by'], unique=False)
    op.create_index(op.f('ix_procurement_requests_vendor_id'), 'procurement_requests', ['vendor_id'], unique=False)
    op.create_foreign_key(None, 'procurement_requests', 'vendors', ['vendor_id'], ['id'])
    op.add_column('purchase_orders', sa.Column('tax_details', sa.Float(), nullable=True))
    op.add_column('purchase_orders', sa.Column('shipping_address', sa.String(length=500), nullable=True))
    op.add_column('purchase_orders', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('purchase_orders', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('purchase_orders', sa.Column('po_date', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('purchase_orders_po_number_key'), 'purchase_orders', type_='unique')
    op.drop_constraint(op.f('purchase_orders_procurement_request_id_key'), 'purchase_orders', type_='unique')
    op.create_index(op.f('ix_purchase_orders_approved_by'), 'purchase_orders', ['approved_by'], unique=False)
    op.create_index(op.f('ix_purchase_orders_created_by'), 'purchase_orders', ['created_by'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_procurement_request_id'), 'purchase_orders', ['procurement_request_id'], unique=True)
    op.create_foreign_key(None, 'purchase_orders', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'purchase_orders', 'users', ['created_by'], ['id'])
    op.add_column('users', sa.Column('mobile_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('employee_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    op.add_column('vendor_approval_history', sa.Column('action_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_vendor_approval_history_acted_by'), 'vendor_approval_history', ['acted_by'], unique=False)
    op.create_index(op.f('ix_vendor_approval_history_action_date'), 'vendor_approval_history', ['action_date'], unique=False)
    op.drop_column('vendor_approval_history', 'acted_at')
    op.create_index(op.f('ix_vendors_approval_status'), 'vendors', ['approval_status'], unique=False)
    op.create_index(op.f('ix_vendors_gst_number'), 'vendors', ['gst_number'], unique=True)
    op.create_index(op.f('ix_vendors_pan_number'), 'vendors', ['pan_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_pan_number'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_gst_number'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_approval_status'), table_name='vendors')
    op.add_column('vendor_approval_history', sa.Column('acted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_vendor_approval_history_action_date'), table_name='vendor_approval_history')
    op.drop_index(op.f('ix_vendor_approval_history_acted_by'), table_name='vendor_approval_history')
    op.drop_column('vendor_approval_history', 'action_date')
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'employee_id')
    op.drop_column('users', 'mobile_number')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_orders_procurement_request_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_created_by'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_approved_by'), table_name='purchase_orders')
    op.create_unique_constraint(op.f('purchase_orders_procurement_request_id_key'), 'purchase_orders', ['procurement_request_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('purchase_orders_po_number_key'), 'purchase_orders', ['po_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('purchase_orders', 'po_date')
    op.drop_column('purchase_orders', 'approved_by')
    op.drop_column('purchase_orders', 'created_by')
    op.drop_column('purchase_orders', 'shipping_address')
    op.drop_column('purchase_orders', 'tax_details')
    op.drop_constraint(None, 'procurement_requests', type_='foreignkey')
    op.drop_index(op.f('ix_procurement_requests_vendor_id'), table_name='procurement_requests')
    op.drop_index(op.f('ix_procurement_requests_requested_by'), table_name='procurement_requests')
    op.drop_index(op.f('ix_procurement_requests_request_number'), table_name='procurement_requests')
    op.drop_index(op.f('ix_procurement_requests_priority'), table_name='procurement_requests')
    op.drop_index(op.f('ix_procurement_requests_approved_by'), table_name='procurement_requests')
    op.create_unique_constraint(op.f('procurement_requests_request_number_key'), 'procurement_requests', ['request_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('procurement_requests', 'business_justification',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('procurement_requests', 'priority',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('procurement_requests', 'required_delivery_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('procurement_requests', 'estimated_budget',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('procurement_requests', 'product_category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('procurement_requests', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('procurement_requests', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_vendor_reliability_scores_vendor_id'), table_name='vendor_reliability_scores')
    op.drop_index(op.f('ix_vendor_reliability_scores_risk_level'), table_name='vendor_reliability_scores')
    op.drop_index(op.f('ix_vendor_reliability_scores_id'), table_name='vendor_reliability_scores')
    op.drop_table('vendor_reliability_scores')
    op.drop_index(op.f('ix_supplier_reliability_ranking_vendor_id'), table_name='supplier_reliability_ranking')
    op.drop_index(op.f('ix_supplier_reliability_ranking_rank_position'), table_name='supplier_reliability_ranking')
    op.drop_index(op.f('ix_supplier_reliability_ranking_id'), table_name='supplier_reliability_ranking')
    op.drop_table('supplier_reliability_ranking')
    op.drop_index(op.f('ix_reliability_history_vendor_id'), table_name='reliability_history')
    op.drop_index(op.f('ix_reliability_history_recorded_at'), table_name='reliability_history')
    op.drop_index(op.f('ix_reliability_history_id'), table_name='reliability_history')
    op.drop_table('reliability_history')
    op.drop_index(op.f('ix_procurement_risk_levels_vendor_id'), table_name='procurement_risk_levels')
    op.drop_index(op.f('ix_procurement_risk_levels_risk_level'), table_name='procurement_risk_levels')
    op.drop_index(op.f('ix_procurement_risk_levels_id'), table_name='procurement_risk_levels')
    op.drop_table('procurement_risk_levels')
    op.drop_index(op.f('ix_procurement_recommendations_vendor_id'), table_name='procurement_recommendations')
    op.drop_index(op.f('ix_procurement_recommendations_recommendation_status'), table_name='procurement_recommendations')
    op.drop_index(op.f('ix_procurement_recommendations_id'), table_name='procurement_recommendations')
    op.drop_index(op.f('ix_procurement_recommendations_generated_at'), table_name='procurement_recommendations')
    op.drop_index(op.f('ix_procurement_recommendations_category_id'), table_name='procurement_recommendations')
    op.drop_table('procurement_recommendations')
    # ### end Alembic commands ###
