import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { AuthService } from '../../core/services/auth.service';
import { environment } from '../../../environments/environment';

type ApiRecord = Record<string, unknown>;
interface ChartSeries { title: string; labels: string[]; datasets: { label?: string; data: number[]; backgroundColor?: string | string[] }[]; }
interface ChartResponse { monthlyExpensesChart?: ChartSeries; vendorPerformanceTrendChart?: ChartSeries; categoryDistributionChart?: ChartSeries; contractStatusChart?: ChartSeries; }
interface Metric { label: string; value: string; note: string; tone: string; }

@Component({
  selector: 'app-analytics', standalone: true, imports: [CommonModule],
  template: `
    <section class="analytics-page">
      <header class="page-header"><div><p class="eyebrow">Module 8 · Dashboard analytics</p><h2>{{ title() }}</h2><p>{{ description() }}</p></div><button type="button" class="btn btn-outline-primary" (click)="load()" [disabled]="loading()">{{ loading() ? 'Refreshing…' : 'Refresh data' }}</button></header>
      <div *ngIf="errorMessage()" class="message error-message" role="alert">{{ errorMessage() }}</div>
      <div class="kpi-grid" *ngIf="metrics().length; else loadingState"><article *ngFor="let metric of metrics()" class="kpi-card" [class]="'kpi-card tone-' + metric.tone"><span>{{ metric.label }}</span><strong>{{ metric.value }}</strong><small>{{ metric.note }}</small></article></div>
      <ng-template #loadingState><div class="empty-state" *ngIf="loading()">Loading analytics…</div><div class="empty-state" *ngIf="!loading() && !errorMessage()">No analytic metrics are returned for this workspace yet.</div></ng-template>
      <section class="chart-grid" *ngIf="charts() as chartData"><article class="chart-card" *ngFor="let chart of chartList(chartData)"><h3>{{ chart.title }}</h3><div *ngIf="chart.datasets[0]?.data?.length; else noChart" class="bars"><div *ngFor="let value of chart.datasets[0].data; let index=index" class="bar-column"><span class="bar" [style.height.%]="value / max(chart.datasets[0].data) * 100"></span><b>{{ formatValue(value) }}</b><small>{{ chart.labels[index] || 'Unlabelled' }}</small></div></div><ng-template #noChart><p class="empty-state compact">The backend returned no chart-ready values for this dataset.</p></ng-template></article></section>
      <section class="detail-panel" *ngIf="details().length"><h3>Live data notes</h3><dl><div *ngFor="let item of details()"><dt>{{ item.label }}</dt><dd>{{ item.value }}</dd></div></dl></section>
    </section>`,
  styles: [`
    .analytics-page{color:var(--vr-navy)}.kpi-card{display:grid;gap:.18rem}.kpi-card small{color:var(--vr-muted);font-size:.7rem}.chart-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:.75rem;margin-top:.8rem}.chart-card,.detail-panel{padding:.85rem .95rem;border:1px solid var(--vr-border);border-radius:13px;background:#fff;box-shadow:0 6px 16px rgba(15,23,42,.05)}.chart-card h3,.detail-panel h3{margin:0 0 .65rem;font-size:.95rem}.bars{display:flex;align-items:flex-end;gap:.5rem;min-height:138px;padding-top:.55rem;border-bottom:1px solid #f4d8df}.bar-column{display:grid;min-width:30px;flex:1;align-items:end;gap:.2rem;text-align:center}.bar{display:block;min-height:3px;border-radius:6px 6px 0 0;background:linear-gradient(180deg,#fb7185,#e11d48)}.bar-column b{font-size:.7rem}.bar-column small{overflow:hidden;color:var(--vr-muted);font-size:.65rem;text-overflow:ellipsis;white-space:nowrap}.detail-panel{margin-top:.8rem}.detail-panel dl{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:.6rem;margin:0}.detail-panel dl div{padding:.6rem .7rem;border-radius:9px;background:#fff7f8}.detail-panel dt{color:var(--vr-muted);font-size:.72rem}.detail-panel dd{margin:.2rem 0 0;font-weight:750}.compact{padding:.7rem}@media(max-width:600px){.bars{gap:.3rem}.bar-column{min-width:22px}}
  `]
})
export class AnalyticsComponent implements OnInit {
  private readonly http = inject(HttpClient); private readonly auth = inject(AuthService); private readonly baseUrl = environment.apiUrl;
  readonly loading = signal(false); readonly errorMessage = signal(''); readonly metrics = signal<Metric[]>([]); readonly details = signal<{label:string;value:string}[]>([]); readonly charts = signal<ChartResponse | null>(null); readonly title = signal('Analytics'); readonly description = signal('Live operational, performance, and risk data returned by the backend.');
  ngOnInit(): void { this.load(); }
  load(): void { const role=this.auth.getUserRole(); this.loading.set(true);this.errorMessage.set('');this.metrics.set([]);this.details.set([]);this.charts.set(null); if(['Administrator','Procurement Manager','Supply Chain Manager','Auditor'].includes(role ?? '')){this.http.get<ChartResponse>(`${this.baseUrl}/dashboard/charts`).subscribe({next:(charts)=>this.charts.set(charts),error:()=>this.charts.set(null)});} if(role==='Administrator'){this.title.set('System analytics');this.description.set('A global view of vendor, procurement, compliance, and operational activity.');this.loadAdmin();return;}if(role==='Procurement Manager'||role==='Supply Chain Manager'){this.title.set('Procurement analytics');this.description.set('Procurement volume, delivery progress, spend, and supplier performance from live aggregation APIs.');this.loadProcurement();return;}if(role==='Vendor'){this.title.set('Vendor analytics');this.description.set('Your linked vendor performance, procurement activity, contracts, and communication summary.');this.loadVendor();return;}this.title.set(`${role || 'Role'} analytics`);this.description.set('Contract, compliance, document, and notification metrics available to your authenticated role.');this.loadModuleSix(); }
  chartList(charts: ChartResponse): ChartSeries[] { return [charts.monthlyExpensesChart,charts.vendorPerformanceTrendChart,charts.categoryDistributionChart,charts.contractStatusChart].filter((chart):chart is ChartSeries=>!!chart); }
  max(data:number[]):number{return Math.max(...data,1)} formatValue(value:number):string{return Number.isInteger(value)?String(value):value.toFixed(1)}
  private loadAdmin():void{this.http.get<ApiRecord>(`${this.baseUrl}/dashboard/admin`).subscribe({next:(data)=>{this.metrics.set([{label:'Total vendors',value:this.number(data,'totalVendors').toString(),note:'All registered vendors',tone:'primary'},{label:'Approved vendors',value:this.number(data,'approvedVendors').toString(),note:'Approved supplier records',tone:'success'},{label:'Procurement requests',value:this.number(data,'totalProcurementRequests').toString(),note:'All recorded requests',tone:'info'},{label:'Purchase orders',value:this.number(data,'totalPurchaseOrders').toString(),note:'All recorded purchase orders',tone:'warning'}]);this.details.set([{label:'Total users',value:String(this.number(data,'totalUsers'))},{label:'Active users',value:String(this.number(data,'activeUsers'))},{label:'Contract portfolio value',value:this.money(this.number(data,'totalContractValue'))},{label:'Compliance vendors',value:String(this.number(data,'compliantVendorsCount'))}]);this.done();},error:(error)=>this.fail(error)});}
  private loadProcurement():void{this.http.get<ApiRecord>(`${this.baseUrl}/dashboard/procurement`).subscribe({next:(data)=>{const summary=this.object(data,'procurementSummary');const delivery=this.object(data,'deliverySummary');this.metrics.set([{label:'Procurement requests',value:String(this.number(summary,'totalRequests')),note:'Current aggregation total',tone:'primary'},{label:'Pending approvals',value:String(this.number(summary,'pendingApprovals')),note:'Requests awaiting action',tone:'warning'},{label:'Active purchase orders',value:String(this.number(summary,'activePurchaseOrders')),note:'Operational orders',tone:'success'},{label:'Procurement spend',value:this.money(this.number(summary,'totalProcurementCost')),note:'Persisted PO totals',tone:'info'}]);this.details.set([{label:'Completed orders',value:String(this.number(summary,'completedOrders'))},{label:'Delayed deliveries',value:String(this.number(delivery,'delayedDeliveries'))},{label:'On-time deliveries',value:String(this.number(delivery,'onTimeDeliveries'))},{label:'Monthly spending',value:this.money(this.number(summary,'monthlySpending'))}]);this.done();},error:(error)=>this.fail(error)});}
  private loadVendor():void{this.http.get<ApiRecord>(`${this.baseUrl}/dashboard/vendor`).subscribe({next:(data)=>{this.metrics.set([{label:'Reliability score',value:this.score(data,'reliabilityScore'),note:'Latest persisted reliability',tone:'success'},{label:'Performance score',value:this.score(data,'overallPerformanceScore'),note:'Latest performance record',tone:'primary'},{label:'Active orders',value:String(this.number(data,'activePurchaseOrders')),note:'Current purchase orders',tone:'info'},{label:'Unread messages',value:String(this.number(data,'unreadMessages')),note:'Communication activity',tone:'warning'}]);this.details.set([{label:'Completed orders',value:String(this.number(data,'completedOrders'))},{label:'Active contracts',value:String(this.number(data,'activeContracts'))},{label:'Pending deliveries',value:String(this.number(data,'pendingDeliveries'))},{label:'Unread notifications',value:String(this.number(data,'unreadNotifications'))}]);this.done();},error:(error)=>this.fail(error)});}
  private loadModuleSix():void{this.http.get<ApiRecord>(`${this.baseUrl}/dashboard`).subscribe({next:(data)=>{const contracts=this.object(data,'contracts');const compliance=this.object(data,'compliance');const documents=this.object(data,'documents');const notifications=this.object(data,'notifications');this.metrics.set([{label:'Active contracts',value:String(this.number(contracts,'activeContracts')),note:'Contract repository',tone:'success'},{label:'Pending compliance',value:String(this.number(compliance,'pendingCount')),note:'Verification records',tone:'warning'},{label:'Documents',value:String(this.number(documents,'totalDocuments')),note:'Vendor document records',tone:'primary'},{label:'Unread alerts',value:String(this.number(notifications,'unreadNotifications')),note:'In-app notifications',tone:'info'}]);this.details.set([{label:'Expired contracts',value:String(this.number(contracts,'expiredContracts'))},{label:'Non-compliant',value:String(this.number(compliance,'nonCompliantCount'))},{label:'Certifications',value:String(this.number(documents,'totalCertifications'))},{label:'Total notifications',value:String(this.number(notifications,'totalNotifications'))}]);this.done();},error:(error)=>this.fail(error)});}
  private done():void{this.loading.set(false)} private fail(error:unknown):void{const detail=typeof error==='object'&&error!==null&&'error' in error?(error as {error?:{detail?:unknown}}).error?.detail:null;this.errorMessage.set(typeof detail==='string'?detail:'Analytics could not be loaded for this account.');this.loading.set(false)} private object(data:ApiRecord,key:string):ApiRecord{return typeof data[key]==='object'&&data[key]!==null?data[key] as ApiRecord:{}} private number(data:ApiRecord,...keys:string[]):number{const value=keys.map(k=>data[k]).find(v=>v!==undefined&&v!==null);return typeof value==='number'?value:Number(value)||0}private score(data:ApiRecord,key:string):string{return this.number(data,key).toFixed(1)}private money(value:number):string{return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value)}
}
