import { CommonModule } from '@angular/common';
import { Component, Input, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { IssueTrackingService, VendorIssue } from '../core/services/issue-tracking.service';

@Component({ selector: 'app-issue-panel', standalone: true, imports: [CommonModule, FormsModule], template: `<section class="issue-panel"><h3>Issues and complaints</h3><p>Open and resolved vendor issues form part of the performance history.</p><p *ngIf="error()" class="message error-message">{{ error() }}</p><form *ngIf="canManage" (ngSubmit)="add()"><input class="form-control" [(ngModel)]="category" name="category" placeholder="Issue category" required><select class="form-select" [(ngModel)]="severity" name="severity"><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select><input class="form-control" type="number" [(ngModel)]="purchaseOrderId" name="po" placeholder="PO ID (optional)"><textarea class="form-control" [(ngModel)]="description" name="description" placeholder="Describe the issue" required></textarea><button class="btn btn-outline-primary">Log issue</button></form><table *ngIf="issues().length"><thead><tr><th>Category</th><th>Severity</th><th>PO</th><th>Status</th><th>Reported</th><th></th></tr></thead><tbody><tr *ngFor="let issue of issues()"><td>{{ issue.category }}</td><td>{{ issue.severity }}</td><td>{{ issue.purchase_order_id || '—' }}</td><td>{{ issue.status }}</td><td>{{ issue.reported_date | date:'mediumDate' }}</td><td *ngIf="canManage && issue.status !== 'Resolved'"><button class="btn btn-sm btn-outline-success" (click)="resolve(issue)">Resolve</button></td></tr></tbody></table><p *ngIf="!issues().length" class="muted">No issue records are available.</p></section>`, styles: [`section{margin-top:1rem}.issue-panel p{color:var(--vr-muted)}form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.6rem;margin:1rem 0}textarea{grid-column:span 2}table{width:100%;border-collapse:collapse}th,td{padding:.65rem;border-bottom:1px solid var(--vr-border);text-align:left}.muted{color:var(--vr-muted)}@media(max-width:700px){form{grid-template-columns:1fr}textarea{grid-column:auto}}`] })
export class IssuePanelComponent {
  private readonly service = inject(IssueTrackingService); @Input({ required: true }) vendorId!: number; @Input() canManage = false;
  readonly issues = signal<VendorIssue[]>([]); readonly error = signal(''); category = ''; severity = 'Medium'; description = ''; purchaseOrderId: number | null = null;
  ngOnChanges(): void { if (this.vendorId) this.load(); }
  load(): void { this.service.list(this.vendorId).subscribe({ next: issues => this.issues.set(issues), error: () => this.error.set('Issue tracking is not available yet.') }); }
  add(): void { if (!this.category.trim() || !this.description.trim()) return; this.service.create(this.vendorId, { category: this.category.trim(), severity: this.severity, description: this.description.trim(), purchase_order_id: this.purchaseOrderId }).subscribe({ next: () => { this.category = ''; this.description = ''; this.purchaseOrderId = null; this.load(); }, error: () => this.error.set('Unable to log issue.') }); }
  resolve(issue: VendorIssue): void { const notes = window.prompt('Resolution notes'); const id = issue.issue_id ?? issue.id; if (!notes || !id) return; this.service.resolve(this.vendorId, id, notes).subscribe({ next: () => this.load(), error: () => this.error.set('Unable to resolve issue.') }); }
}
